version: "3.9"
services:
  backend:
#    build:
#     context: ./backend
    image: oriyazec/backend-app:1
    container_name: calisthenics-backend
    ports:
      - "4000:4000"
    restart: unless-stopped

  frontend:
#    build:
#      context: ./frontend
    image: oriyazec/frontend-app:1  
    container_name: calisthenics-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped

